#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running build check..."
npx --no-install next build

if [ $? -ne 0 ]; then
  echo "Build failed. Please fix the issues before committing."
  exit 1
fi
